//
//  PCSearchResultItem.h
//  Pad CMS
//
//  Created by Oleg Zhitnik on 01.03.12.
//  Copyright (c) 2012 Adyax. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "PCRevision.h"

/**
 @class PCSearchResultItem
 @brief This class contains result item generated by searching task
 */
@interface PCSearchResultItem : NSObject

/**
 @brief Issue (magazine) title
 */ 
@property (nonatomic, retain) NSString *issueTitle;

/**
 @brief Page title
 */ 
@property (nonatomic, retain) NSString *pageTitle;

/**
 @brief Revision identifier
 */ 
@property (nonatomic, assign) NSInteger revisionIdentifier;

/**
 @brief Page index of issue (zero-based)
 */ 
@property (nonatomic, assign) NSInteger pageIndex;


/**
 @brief Returns new initialized instance of the PCSearchResultItem class
 @param _issueTitle - title of magazine that contains keyphrase
 @param _pageTitle - title of page that contains keyphrase
 @param _revision - revision of issue
 @param _pageIndex - index of page that contains keyphrase
 */
-(id) initWithIssueTitle:(NSString*) _issueTitle
            andPageTitle:(NSString*) _pageTitle
   andRevisionIdentifier:(NSInteger) _revisionIdentifier
            andPageIndex:(NSInteger) _pageIndex;
@end
